### ISSUE TITLE
你好，我希望实现一个Android版本的，请问你的动画还有布局是什么思路？

### ISSUE THREAD

**Issue by johnscliang** [JxbSir/JxbLovelyLogin#1]
还没玩过ios开发，ios好像没有布局文件的对吧？你的图，切得不是很对称。
我用Android实现了一下，另外还切了一下你的图，还差一个动画，不知道是什么思路。
你是一帧一帧实现的吗？还是通过ios的什么方法。
Android实现，有兴趣的朋友一起来开发吧：https://github.com/LanceCong/AndroidLovelyLogin

**Comment by JxbSir** [comment]
利用位移来做的
